name: Build and package releases
on:
  release:
    types: [created,edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - name: Install dependencies
        run: npm install

      - name: Clean
        run: rm -rf build
      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_LOGIN_BASE_URL: https://search-staging.www.lib.umich.edu
          REACT_APP_SPECTRUM_BASE_URL: https://search-staging.www.lib.umich.edu/spectrum
      - name: Package
        run: tar -C build --transform s/./search/ -czf search-staging.tar.gz .
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          files: search-staging.tar.gz

      - name: Clean
        run: rm -rf build
      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_LOGIN_BASE_URL: https://search.lib.umich.edu
          REACT_APP_SPECTRUM_BASE_URL: https://search.lib.umich.edu/spectrum
      - name: Package
        run: tar -C build --transform s/./search/ -czf search-production.tar.gz .
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          files: search-production.tar.gz

      - name: Clean
        run: rm -rf build
      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_LOGIN_BASE_URL: http://127.0.0.1:3000
          REACT_APP_SPECTRUM_BASE_URL: http://127.0.0.1:3000/spectrum
      - name: Package
        run: tar -C build --transform s/./search/ -czf search-local.tar.gz .
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          files: search-local.tar.gz
